spring:
  datasource:
    url: jdbc:postgresql://34.101.197.21:5435/db-inventory
    username: lyzhia
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
